Fi 1000 fix splitting scope with extra spaces
inferno-community/inferno-reference-server pull request #20
Opened 2020-09-22 09:17 UTC by hershilpatel

Reference server now allows each scope in a scope string to be separated by multiple spaces

2020-10-05 14:06 UTC, Jammjammjamm reviewed
When I visit: http://localhost:8080/reference-server/oauth/authorization?response_type=code&client_id=SAMPLE_CONFIDENTIAL_CLIENT_ID&redirect_uri=http%3A%2F%2Flocalhost%3A4567%2Finferno%2Foauth2%2Fstatic%2Fredirect&scope=+launch+launch%2Fpatient++++offline_access+openid+profile++user%2F*.*+patient%2F*.*+++&state=eb1c05fe-122f-4cd0-aac6-8535f14cd1a2&aud=http%3A%2F%2Flocalhost%3A8080%2Freference-server%2Fr4&patient_id=18

I see this:

![Screen Shot 2020-10-05 at 10 04 23 AM](https://user-images.githubusercontent.com/15969967/95089575-4be3ba80-06f2-11eb-9cc6-634c2508ef36.png)

2020-10-06 12:22 UTC, okeefm requested changes
I'm seeing the same issue as @Jammjammjamm.

2020-10-14 12:08 UTC, okeefm approved these changes
Works as expected now. Looks good!

2020-10-14 13:13 UTC, radamson reviewed
Works great!  Left a couple minor code suggestions for your consideration.

2020-10-22 13:35 UTC, radamson commented on src/main/java/org/mitre/fhir/utils/FhirReferenceServerUtils.java
> +    return scopesList;
What's the verdict on this? 👍 👎

2020-10-26 13:58 UTC, Jammjammjamm approved these changes

2020-10-26 14:04 UTC, radamson approved these changes

2020-10-26 16:07 UTC, merged