Landing page
inferno-community/inferno-reference-server pull request #29
Opened 2020-12-01 16:00 UTC by hershilpatel

Added landing page at localhost/reference-server

<img width="1224" alt="Screen Shot 2020-12-02 at 11 06 30 AM" src="https://user-images.githubusercontent.com/51918208/100898782-1dceec80-348f-11eb-8985-768170e6ba5c.png">

2020-12-01 19:24 UTC, Jammjammjamm commented on src/main/webapp/WEB-INF/templates/landing.html
> +   		This server is designed to meet the Inferno Program Certification Tests.
You should use some p tags. HTML doesn't respect whitespace.

2020-12-01 19:24 UTC, Jammjammjamm commented on src/main/webapp/WEB-INF/templates/landing.html
> +   		<div class="card card-body bg-light">
I don't see why this list is styled differently than the other lists.

2020-12-01 19:24 UTC, Jammjammjamm commented on src/main/webapp/WEB-INF/templates/landing.html
> +			<li>.well-known URL</li>
I don't know that this is worth listing. It's a requirement.

2020-12-01 21:04 UTC, hershilpatel commented on src/main/webapp/WEB-INF/templates/landing.html
> +   		This server is designed to meet the Inferno Program Certification Tests.
Added p tags

2020-12-01 21:04 UTC, hershilpatel commented on src/main/webapp/WEB-INF/templates/landing.html
> +			<li>.well-known URL</li>
Removed unnecessary list

2020-12-02 13:32 UTC, Jammjammjamm commented on src/main/webapp/WEB-INF/templates/landing.html
> +			<li>.well-known URL</li>
I just meant the `.well-known URL` entry.

2020-12-02 16:08 UTC, hershilpatel commented on src/main/webapp/WEB-INF/templates/landing.html
> +			<li>.well-known URL</li>
My mistake, re-adding

2020-12-02 16:09 UTC, hershilpatel commented on src/main/webapp/WEB-INF/templates/landing.html
> +   		<div class="card card-body bg-light">
Removed different styling

2020-12-02 16:57 UTC, okeefm reviewed
Couple quick suggestions, otherwise, looks good

2020-12-02 16:57 UTC, okeefm commented on src/main/webapp/WEB-INF/templates/landing.html
> +   		<p>This server is designed to meet the Inferno Program Certification Tests.  This includes:</p>
```suggestion
   		<p>This server is designed to meet the requirements of the Inferno Program Certification Tests.  This includes:</p>
```

2020-12-02 16:57 UTC, okeefm commented on src/main/webapp/WEB-INF/templates/landing.html
> +<p>Support for US Core v3.1.0, including:</p>
Should we bump this to `v3.1.1`, since we're about to release 3.1.1 support?
```suggestion
<p>Support for US Core v3.1.1, including:</p>
```

2020-12-11 16:47 UTC, arscan commented on src/main/webapp/WEB-INF/templates/landing.html
> +<!-- Normally this will be a site to accept a user name and password and log in to determine which code to send, for now it'll just redirect-->
?

2020-12-11 16:48 UTC, arscan commented on src/main/webapp/WEB-INF/templates/landing.html
> +  <link href="../reference-server/app/css/site.css" rel="stylesheet">
why the `../reference-server/`?  Would just `/reference-server/` do?

2020-12-11 16:49 UTC, arscan commented on src/main/webapp/WEB-INF/templates/landing.html
> +  <meta name="description" content="Authorize Cindehr">
I'm not sure this description makes sense anymore.

2020-12-11 16:53 UTC, arscan commented on src/main/webapp/WEB-INF/templates/landing.html
> +   			<li><a href="/reference-server/r4/metadata">Conformance</a></li>
It is now called a 'Capability Statement'.  I think a link to the endpoint itself might be more useful (even though it won't actually do anything in a browser).  I could imagine going to this page and wanting to grab all the config info I would need to run inferno against it. Which would be the fhir endpoint, and the confidential/public client details.

2020-12-11 19:43 UTC, hershilpatel commented on src/main/webapp/WEB-INF/templates/landing.html
> +<!-- Normally this will be a site to accept a user name and password and log in to determine which code to send, for now it'll just redirect-->
copy and paste error, removing that line

2020-12-11 23:23 UTC, hershilpatel commented on src/main/webapp/WEB-INF/templates/landing.html
> +   			<li><a href="/reference-server/r4/metadata">Conformance</a></li>
added section  for fhir endpoint, client id, and client secret

2020-12-14 14:47 UTC, arscan commented on src/main/webapp/WEB-INF/templates/landing.html
> +   			<li><a href="/reference-server/r4/metadata">Conformance</a></li>
Could you also add the public client id?  So maybe the order is "Public Client ID: XYZ" then "Confidential Client ID: ABC" and "Confidential Client Secret: DEF".

2020-12-14 14:53 UTC, arscan commented on src/main/webapp/WEB-INF/templates/landing.html
> +   			<li><a href="/reference-server/r4/metadata">Conformance</a></li>
(ideally these values would be driven from the constant defined in the app also, because it makes me a little uncomfortable to have the same thing repeated in multiple places, but it seems unlikely that we'll mess with these so that isn't a huge deal to me, just mentioning it as more of a best practice)

2020-12-16 21:33 UTC, arscan commented on src/main/java/org/mitre/fhir/utils/FhirReferenceServerUtils.java
> +  //    "SAMPLE_CONFIDENTIAL_CLIENT_SECRET";
Try to get in the habit of reviewing your diffs before committing and deleting commented out code (unless it serves a good purpose, but I'm not seeing what that purpose might be in this case).

2020-12-16 21:49 UTC, arscan approved these changes

2020-12-18 16:22 UTC, okeefm requested changes
Just a couple of Javadoc comment changes, otherwise looks good!

2020-12-18 16:22 UTC, okeefm commented on src/main/java/org/mitre/fhir/HapiReferenceServerProperties.java
> +   * Returns the Hibernate Property.
Is this property (and the two below) actually a `Hibernate` property?
```suggestion
   * Returns the public Client ID Property.
```

2020-12-18 16:22 UTC, okeefm commented on src/main/java/org/mitre/fhir/HapiReferenceServerProperties.java
> +   * Returns the Hibernate Property.
```suggestion
   * Returns the Confidential Client ID Property.
```

2020-12-18 16:22 UTC, okeefm commented on src/main/java/org/mitre/fhir/HapiReferenceServerProperties.java
> +   * Returns the Hibernate Property.
```suggestion
   * Returns the Confidential Client Secret Property.
```

2020-12-18 18:25 UTC, okeefm approved these changes
Looks good!

2020-12-18 18:25 UTC, merged